version: '3'

services:
  php:
    container_name: php-utils
    build:
      context: .docker/php
      args:
        - WITH_XDEBUG=true
    volumes:
      - ./:/var/www
      - ./log/:/var/log
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/php.ini
  composer:
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: composer-utils
    image: composer:2
    volumes:
      - ./:/app
    working_dir: /app
    command: composer update --ignore-platform-reqs --no-dev
