version: '3'

services:
  php:
    container_name: php-utils
    build:
      context: ./php
      args:
        - WITH_XDEBUG=true
    networks:
      - shared
    volumes:
      - ../:/var/www
      - ../log/:/var/log
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    container_name: nginx-utils
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared
    depends_on:
      - php
    tty: true

  mariadb:
    container_name: mariadb-general
    build:
      context: ./mariadb
    env_file:
      - conf/mariadb/db.env
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - shared

networks:
  shared:
    external: true